# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [1]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
array = np.zeros(10)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### Create an array of 10 ones

In [3]:
array = np.ones(10)
print(array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [5]:
array = np.full(10, 5)
print(array)

[5 5 5 5 5 5 5 5 5 5]


#### Create an array of the integers from 10 to 50

In [6]:
array = np.arange(10,51)
print(array)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Create an array of all the even integers from 10 to 50

In [7]:
array = np.arange(10,51, 2)
print(array)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
matrix = np.arange(0, 9).reshape(3,3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [9]:
matrix = np.identity(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [10]:
random_number = np.random.randint(0,1)
print(random_number)

0


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [11]:
random_numbers = np.random.standard_normal(25)
print(random_numbers)

[ 0.73435243  0.35144105  0.4576455  -0.86233849  0.32686546  0.36907114
  0.4274736  -1.60825884 -0.40312229 -0.07886737  0.13582006 -0.36404323
 -1.01071215 -0.67306052 -1.91356472  0.21031032  0.25711616  0.3624245
  0.02696678  0.80093578  0.41109769  0.17485122 -0.38899302  0.70802972
 -0.7162926 ]


#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
array = np.linspace(0,1 ,20)
array

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [13]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [14]:
sum = np.sum(mat)
sum

325

#### Get the standard deviation of the values in mat

In [15]:
standard_deviation = np.std(mat)
standard_deviation

7.211102550927978

#### Get the sum of all the columns in mat

In [16]:
sum_of_columns = np.sum(mat, axis=0)
sum_of_columns

array([55, 60, 65, 70, 75])

# Great Job!